apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
    kubernetes.io/cluster-service: "true"
  name: heapster
spec:
  replicas: 1
  selector:
      matchLabels:
          k8s-app: heapster
          version: v6
  template:
      metadata:
          labels:
              k8s-app: heapster
              version: v6
      spec:
        serviceAccountName: "io-rancher-system"
        containers:
        - name: heapster
          image: $GCR_IO_REGISTRY/google_containers/heapster:v1.3.0-beta.0
          imagePullPolicy: Always
          command:
          - /heapster
          - --source=kubernetes:https://10.43.0.1:443?inClusterConfig=true&useServiceAccount=true
          - --sink=influxdb:http://monitoring-influxdb.kube-system.svc.cluster.local:8086
